provider "aws" {
    region = "DELETED FOR GITHUB AND AMAZON NOTIFICATION"
    access_key = "DELETED FOR GITHUB AND AMAZON NOTIFICATION"
    secret_key = "DELETED FOR GITHUB AND AMAZON NOTIFICATION"
}